import { contains } from "cypress/types/jquery"

describe('library feature Test', () => {
    const un = Cypress.env('USERNAME')
    const pwd = Cypress.env('PASSWORD')
    beforeEach(() => {
        cy.library_login(un, pwd)
    })
    it('When user click on library link,should navigate to library page successfully', () => {
        cy.visit('/library')
        cy.url().should('include', '/library')
        cy.contains('Reports').should('be.visible')
        cy.contains('Circulation').should('be.visible')
        cy.get('a:contains(Materials under circulation report )').should('exist')
        cy.get('a:contains(Over-due report )').should('exist')
        cy.get('a:contains(Age analysis )').should('exist')
        cy.get('a:contains(Valuation report )').should('exist')
        cy.get('a:contains(Late fees report )').should('exist')
        cy.get('a:contains(Books without ISBN )').should('exist')
        cy.get('a:contains(Books without synopsis )').should('exist')
        cy.get('a:contains(Books without cover photo )').should('exist')
        cy.get('a:contains(Unverified stock )').should('exist')
    })
    it('When user click on Catalog/Manage link,should navigate to manage successfully', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/manage"]').click({ multiple: true })
        cy.url().should('include', '/manage')
        cy.get('input[placeholder="Search"]').should('exist')
        cy.contains('Add New Library Material').should('be.visible')
        cy.get('a[href="/ctng4/library/add"]').should('exist')
    })
    it('When user click on Catalog/add link,should navigate to catlog/add page successfully', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/add"]').click()
        cy.url().should('include', '/add')
        cy.contains('Library').should('be.visible')
        cy.get('button[class="btn btn-xs btn-success pull-right"]').should('exist')
        cy.get('button[class="btn btn-xs btn-success pull-right"]').should('contain', 'Save')
        cy.get('button[class="btn btn-xs btn-success pull-right"]').should('be.disabled')
        cy.get('input[placeholder="Tracking Id"]').should('exist')
        cy.get('input[placeholder="Title"]').should('exist')
        cy.get('input[placeholder="Author"]').should('exist')
        cy.get('input[placeholder="Publisher"]').should('exist')
        cy.get('input[placeholder="ISBN"]').should('exist')
        cy.get('input[placeholder="Location"]').should('exist')
    })
    it('When user enter valid inputs in textfield of catlog/add , save button should get enable and user should perform click action', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/add"]').click()
        cy.url().should('include', '/add')
        cy.contains('Library').should('be.visible')
        cy.get('button[class="btn btn-xs btn-success pull-right"]').should('be.disabled')
        cy.get('input[placeholder="Tracking Id"]').type(Cypress.env('TRACKING ID'))
        cy.get('input[placeholder="Title"]').type(Cypress.env('TITLE'))
        cy.get('input[placeholder="Author"]').type(Cypress.env('AUTHOR'))
        cy.get('input[placeholder="Publisher"]').type(Cypress.env('PUBLISHER'))
        cy.get('input[placeholder="ISBN"]').type(Cypress.env('ISBN'))
        cy.get('input[placeholder="Location"]').type(Cypress.env('LOCATION'))
        cy.get('button[class="btn btn-xs btn-success pull-right"]').should('be.enabled')
        cy.get('button[class="btn btn-xs btn-success pull-right"]').click()
    })/*
    it('user should able to see details of added material by entering tracking id in textfield of Catalog/Manage page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/manage"]').click()
        cy.get('input[placeholder="Search"]').type(Cypress.env('TRACKING ID')).parent().next().children('i[class="fa fa-search"]').click()
        cy.get('thead').next().children('tr').first().find('a').parent().next().next('td').should('have.text', Cypress.env('AUTHOR')).should('be.visible').should('exist')
    })
    it('When user click on trackin id, user should navigate to edit page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/manage"]').click()
        cy.get('input[placeholder="Search"]').type(Cypress.env('TRACKING ID')).parent().next().children('i[class="fa fa-search"]').click()
        cy.get('thead').next().children('tr').first().find('a').click()
        cy.url().should('include','/library/manage/edit')
        cy.get('div:contains(Info )').should('exist').find('button:contains(Update)').should('exist').should('be.disabled')
        cy.get('input[placeholder="Title"]').should('exist')
        cy.get('input[placeholder="Author"]').should('exist')
        cy.get('input[placeholder="Publisher"]').should('exist')
        cy.get('input[placeholder="ISBN"]').should('exist')
        cy.get('input[placeholder="Location"]').should('exist')
    })*/
    it('user click on circulation link , should navigate to Issue / Return page ', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/circulation"]').click()
        cy.url().should('include', '/library/circulation')
        cy.get('input[placeholder="Search by Tracking Id or Student Id or Staff Id"]').should('exist')
        cy.get('button:contains(Reset)').should('be.enabled').should('exist')
    })
    it('user click on  stockVerification link , should navigate to stockVerification page ', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/stockVerification"]').click()
        cy.url().should('include', '/library/stockVerification')
        cy.get('input[placeholder="Search by Tracking Id"]').should('exist')
        cy.get('h3:contains("Stock Verification")').should('be.visible')
        cy.get('input[placeholder="Search by Tracking Id"]').should('exist')
        cy.get('thead tr th').should(($th) => expect($th).to.have.length(8).and.to.contain('Tracking Id').and.to.contain('Title').and.to.contain('Author').and.to.contain('Publisher').and.to.contain('Details').and.to.contain('Tags').and.to.contain('Value').and.to.contain('Status'));
    })
    it('When user click on Add New Library Material, user should navigate to library/add page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/add"]').click()
        cy.url().should('include', '/add')
        cy.contains('Library').should('be.visible')
        cy.get('button[class="btn btn-xs btn-success pull-right"]').should('be.disabled')
        cy.get('input[placeholder="Tracking Id"]').should('exist')
        cy.get('input[placeholder="Title"]').should('exist')
        cy.get('input[placeholder="Author"]').should('exist')
        cy.get('input[placeholder="Publisher"]').should('exist')
        cy.get('input[placeholder="ISBN"]').should('exist')
        cy.get('input[placeholder="Location"]').should('exist')
        cy.get('button[class="btn btn-xs btn-success pull-right"]').should('be.visible').should('be.disabled')
    })
    it('When user click on Print Barcodes,should navigate to Print Barcodes page  ', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/barcode"]').click()
        cy.url().should('include', '/library/barcode')
        cy.get('strong:contains(Customize)').parent().next().children().find('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('label[for="barcodeRange"]').should("have.text", "Tracking Id(s) to print barcodes").get('label[for="barcodeRange"] p').should("have.text", "print barcodes")
        cy.get('textarea[name="barcodeRange"]').should('exist')
        cy.get('span:contains(Add comma separated tracking ids for which barcodes have to be printed. Ex: 15,18 )').should('be.visible')
        cy.get('span:contains(Add the range of tracking ids for which barcodes have to be printed. Ex: 1-10, 20-25)').should('be.visible')
        cy.get('label:contains(Barcode position)').should('be.visible').next().children('input[name="position"]').should('exist')
        cy.get('label:contains(No. of barcode prints)').should('be.visible').next().children('input[name="printNo"').should('exist')
        cy.get('label:contains(Margin)').should('be.visible').next().children('input[name="marginTop"]').should('exist')
    })
    it('When user click on Summary report ,should navigate to summaryReport page  ', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/summaryReport"]').click()
        cy.url().should('include', '/library/summaryReport')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled') 
    })
    it('When user click on Materials under circulation report  link, should navigate to Materials under circulation report page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/circulationReport"]').click()
        cy.url().should('include', '/library/circulationReport')
        cy.get('h4').should('contain.text', 'Library Material Under Circulation Report')
        cy.get('button[title="Download As PDF"]').should('be.enabled')
        cy.get('button[title="Print"]').should('be.enabled')
        cy.contains('Report Header').should('be.visible')
        cy.contains('Page Header').should('be.visible')
        cy.contains('Page Header On Each Page').should('be.visible')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/library')
      })
      it('When user click on Over-due reportlink, should navigate to Over-duereport page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/overDueReport"]').click()
        cy.url().should('include', '/library/overDueReport')
        cy.get('h4').should('contain.text', 'LibraryOver Due Report')
        cy.get('button[title="Download As PDF"]').should('be.enabled')
        cy.get('button[title="Print"]').should('be.enabled')
        cy.contains('Report Header').should('be.visible')
        cy.contains('Page Header').should('be.visible')
        cy.contains('Page Header On Each Page').should('be.visible')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/library')
      })
      it('When user click on Materials under maintenance report link, should navigate toMaterials under maintenance report page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/maintenanceReport"]').click()
        cy.url().should('include', '/library/maintenanceReport')
        cy.get('h4').should('contain.text', 'Library Material Under Maintenance Report')
        cy.get('button[title="Download As PDF"]').should('be.enabled')
        cy.get('button[title="Print"]').should('be.enabled')
        cy.contains('Report Header').should('be.visible')
        cy.contains('Page Header').should('be.visible')
        cy.contains('Page Header On Each Page').should('be.visible')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/library')
      })
      it('When user click on Age analysis report link, should navigate to Age analysis report page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/ageAnalysisReport"]').click()
        cy.url().should('include', '/library/ageAnalysisReport')
        cy.get('h4').should('contain.text', 'Library Age Analysis Report')
        cy.get('button[title="Download As PDF"]').should('be.enabled')
        cy.get('button[title="Print"]').should('be.enabled')
        cy.contains('Report Header').should('be.visible')
        cy.contains('Page Header').should('be.visible')
        cy.contains('Page Header On Each Page').should('be.visible')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/library')
      })
      it('When user click on Valuation report link, should navigate to Valuation report page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/valuationReport"]').click()
        cy.url().should('include', '/library/valuationReport')
        cy.get('h4').should('contain.text', 'LibraryValuation Report')
        cy.get('button[title="Download As PDF"]').should('be.enabled')
        cy.get('button[title="Print"]').should('be.enabled')
        cy.contains('Report Header').should('be.visible')
        cy.contains('Page Header').should('be.visible')
        cy.contains('Page Header On Each Page').should('be.visible')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/library')
      })
      it('When user click on Late fees report link, should navigate to Late fees report page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/lateFeesReport"]').click()
        cy.url().should('include', '/library/lateFeesReport')
        cy.get('h4').should('contain.text', 'Library Fees Report')
        cy.get('button[title="Download As PDF"]').should('be.enabled')
        cy.get('button[title="Print"]').should('be.enabled')
        cy.contains('Report Header').should('be.visible')
        cy.contains('Page Header').should('be.visible')
        cy.contains('Page Header On Each Page').should('be.visible')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/library')
      })
      it('When user click on Books without ISBN link, should navigate to Books without ISBN report page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/booksWithoutISBNReport"]').click()
        cy.url().should('include', '/library/booksWithoutISBNReport')
        cy.get('h4').should('contain.text', 'Library Books Without ISBN Report')
        cy.get('button[title="Download As PDF"]').should('be.enabled')
        cy.get('button[title="Print"]').should('be.enabled')
        cy.contains('Report Header').should('be.visible')
        cy.contains('Page Header').should('be.visible')
        cy.contains('Page Header On Each Page').should('be.visible')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/library')
      })
      it('When user click on Books without synopsis link, should navigate to Books without synopsis report page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/booksWithoutSynopsisReport"]').click()
        cy.url().should('include', '/library/booksWithoutSynopsisReport')
        cy.get('h4').should('contain.text', 'Library Books Without Synopsis Report')
        cy.get('button[title="Download As PDF"]').should('be.enabled')
        cy.get('button[title="Print"]').should('be.enabled')
        cy.contains('Report Header').should('be.visible')
        cy.contains('Page Header').should('be.visible')
        cy.contains('Page Header On Each Page').should('be.visible')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/library')
      })
      it('When user click on Books without cover photo link, should navigate to Books without cover photo report page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/booksWithoutCoverPhotoReport"]').click()
        cy.url().should('include', '/library/booksWithoutCoverPhotoReport')
        cy.get('h4').should('contain.text', 'Library Books Without Cover Photo Report')
        cy.get('button[title="Download As PDF"]').should('be.enabled')
        cy.get('button[title="Print"]').should('be.enabled')
        cy.contains('Report Header').should('be.visible')
        cy.contains('Page Header').should('be.visible')
        cy.contains('Page Header On Each Page').should('be.visible')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/library')
      })
      it('When user click on Unverified stock link, should navigate to Unverified stock report page', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/unverifiedStockReport"]').click()
        cy.url().should('include', '/library/unverifiedStockReport')
        cy.get('h4').should('contain.text', 'Library Unverified Stock Report')
        cy.get('button[title="Download As PDF"]').should('be.enabled')
        cy.get('button[title="Print"]').should('be.enabled')
        cy.contains('Report Header').should('be.visible')
        cy.contains('Page Header').should('be.visible')
        cy.contains('Page Header On Each Page').should('be.visible')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/library')
      })
    it('Verify back button in catlog feature', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/add"]').click()    
        cy.url().should('eq', Cypress.config().baseUrl + '/library/add')  
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/library')  
        cy.get('a[href="/ctng4/library/manage"]').click()  
        cy.url().should('eq', Cypress.config().baseUrl + '/library/manage') 
        cy.get('a:contains(Add New Library Material)').click()                          
        cy.url().should('eq', Cypress.config().baseUrl + '/library/add')  
        cy.click_Back_Button()    
        cy.url().should('eq', Cypress.config().baseUrl + '/library') 
        cy.get('a[href="/ctng4/library/manage"]').click()  
        cy.url().should('eq', Cypress.config().baseUrl + '/library/manage')
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/library')                       
      })
      it('Verify back button in circulation feature', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/circulation"]').click()    
        cy.url().should('eq', Cypress.config().baseUrl + '/library/circulation')  
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/library')                        
      })
      it('Verify back button in stock Verification feature', () => {
        cy.visit('/library')
        cy.get('a[href="/ctng4/library/stockVerification"]').click()    
        cy.url().should('eq', Cypress.config().baseUrl + '/library/stockVerification')  
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/library')                        
      })
})
