describe('Lms feature Test', () => {
    const un = Cypress.env('USERNAME')
    const pwd = Cypress.env('PASSWORD')
    beforeEach(() => {
        cy.lms_login(un, pwd)
    })
    it('should navigate to lms page successfully ', () => {
        cy.visit('/lms')
        cy.url().should('include', '/lms')
        cy.get('a[href="/ctng4/lms/curriculum/add"]').should('exist')
        cy.get('a[href="/ctng4/lms/qa/add"]').should('exist')
        cy.get('a[href="/ctng4/lms/assessment/add"]').should('exist')
        cy.get('a[href="/ctng4/lms/assessment/taking"]').should('exist')
        cy.get('a[href="/ctng4/lms/curriculum/study"]').should('exist')
    })
    it('when user click on content manage link,should navigate to curriculum page successfully ', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/curriculum"]').click()
        cy.url().should('include', '/curriculum')
        cy.get('input[placeholder="Search"]').should('exist')
        cy.get('a:contains(Add New Content)').should('be.visible')
    })
    it('when user click on Add New Content link,should navigate to curriculum/add page successfully ', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/curriculum/add"]').click()
        cy.url().should('include', '/curriculum/add')
    })
    it('when user click on QA manage link,should navigate to QA manage page successfully ', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/qa"]').click()
        cy.url().should('include', '/lms/qa')
        cy.get('input[placeholder="Search"]').should('exist')
        cy.get('button:contains(Add Question)').should('be.visible').should('exist')
    })
    it('when user click on Add Question button,should navigate to QA add page successfully ', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/qa"]').click()
        cy.get('button:contains(Add Question)').click()
        cy.url().should('include', '/lms/qa/add')
        cy.get('h3').children().find('a:contains(LMS)').should('be.visible').next().siblings('a:contains(QA)').should('be.visible').next().siblings('strong:contains(Add)').should('be.visible')
        cy.get('button:contains(Save)').should('exist')
        cy.contains('label', 'Bulk').siblings('input[type="checkbox"]').should('not.be.checked')
        cy.get('div[class="panel-heading"]').should('exist')
    })
    it('when user click on QA add link,should navigate to QA add page successfully ', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/qa/add"]').click()
        cy.url().should('include', '/lms/qa/add')
        cy.get('h3').children().find('a:contains(LMS)').should('be.visible').next().siblings('a:contains(QA)').should('be.visible').next().siblings('strong:contains(Add)').should('be.visible')
        cy.get('button:contains(Save)').should('exist')
        cy.contains('label', 'Bulk').siblings('input[type="checkbox"]').should('not.be.checked')
        cy.get('div[class="panel-heading"]').should('exist')
    })
    it('when user click on Question tag,User is navigated to Add Questions page on click over Questions tags ,user can add and create tags with respect to questions', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/qa/add"]').click()
        cy.url().should('include', '/lms/qa/add')
        cy.get('h3').children().find('a:contains(LMS)').should('be.visible').next().siblings('a:contains(QA)').should('be.visible').next().siblings('strong:contains(Add)').should('be.visible')
        cy.get('button:contains(Save)').should('exist')
        cy.get('i[class="fa fa-tags"]').click()
        cy.get('input[placeholder="search"]').should('exist')
        cy.get('i[class="fa fa-plus"]').should('exist')
        //cy.get('a:contains(biology)').parents('label').parent().children('input(type="checkbox")').should('exist')
        cy.contains('label', 'biochemistry').siblings('input[type="checkbox"]').should('exist')
        // cy.get('i[class="fa fa-tags"]').click()
        // cy.get('div(class="label label-info")').should('be.visible')
    })
    it('On completely adding the question the user on clicking on add the question is displayed on QA Manage ', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/qa/add"]').click({force: true})
        cy.get('label:contains(Answer Type)').siblings().children().find('label:contains(Text)').should('be.visible').prev('input[value="Text"]').should('exist').parent().siblings().find('label:contains(MCQ)').should('be.visible').prev('input[value="ManyOf"]').should('exist')
        function getRandomItem(arr) {
            const randomIndex = Math.floor(Math.random() * arr.length);
            const item = arr[randomIndex];
            return item;
        }
        const array = ['What was the real name of Mumtaz Mahal?', 'Name the only President to have been elected for two consecutive terms?',
            'The Gandhi - Irwin pact was signed in the year.',
            'The name of the first bank established in India was.',
            ' Who served as the first Deputy Prime Minister of independent India ?',
            'The first Governor-General of India was?'];
        const result = getRandomItem(array);
        console.log(result)
        cy.get('div[class="ace_line"]').click({ force: true })
        const string = getRandomItem(array)
        cy.get('textarea[class="ace_text-input"').type(string, { force: true })
        cy.contains('label', 'indian_history').siblings('input[type="checkbox"]').click({ force: true })
        cy.get('button[class="btn btn-sm btn-success"]').click({force: true})
        cy.url().should('include', 'lms/qa')
    })
    it('when user click on assement add link, User is navigated to Assessment add page', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/assessment/add"]').click()
        cy.url().should('include', '/lms/assessment/add')
        cy.contains('LMS').should('exist')
        cy.contains('Assessment').should('exist')
        cy.contains('Add').should('exist')
        cy.get('button:contains(Save)').should('be.disabled').should('exist')
    })/*
    it('when user click on name of Assessment  link, User is navigated to LMS-Assessment edit page', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/assessment/manage"]').click()
        cy.contains('td', 'ABC').siblings('td').contains('Unit test').click()
        cy.url().should('include', '/lms/assessment/edit')
        cy.contains('LMS').should('exist')
        cy.contains('Assessment').should('exist')
        cy.contains('Edit').should('exist')
        cy.get('button:contains(Update)').should('exist')
    })
    it('User is navigated on QA-Assessment edit should drage the questions published on workspace', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/assessment/manage"]').click()
        cy.contains('td', 'ABC').siblings('td').contains('Unit test').click()
        cy.get('input[placeholder="Search"]').type('what is your name?')
        cy.get('input[placeholder="Search"]').parent().siblings().children('i[class="fa fa-search"]').click()
        //cy.get('i[class="fa fa-search"]').click({ multiple: true })
        cy.contains('what is your name?').parents('.list-group-item').find('.fa.fa-exchange').click();
    })
    it('User should drage the questions published on LMS-Manage page preview the questions dragged', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/assessment/manage"]').click()
        cy.contains('td', 'ABC').siblings('td').contains('Unit test').click()
        cy.get('input[placeholder="Search"]').type('what is your name?')
        cy.get('input[placeholder="Search"]').parent().siblings().children('i[class="fa fa-search"]').click()
        //cy.get('i[class="fa fa-search"]').click({ multiple: true })
        cy.contains('what is your name?').parents('.list-group-item').find('.fa.fa-exchange').click();
        cy.get('a:contains(Preview)').click()
    })
    it('User click on assement manage page,User is navigated to Assessment Manage page ', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/assessment/manage"]').click()
        cy.get('h3').children().find('a:contains(LMS)').should('be.visible').next().siblings('strong:contains(Assessment)').should('be.visible').next().siblings('strong:contains(Manage)').should('be.visible')
        cy.get('input[placeholder="Search"]').should('exist')
        cy.get('a:contains(Add New Assessment)').should('be.visible')
        cy.get('thead tr').should('contain', 'Description').and('contain', 'Subject').and('contain', 'Duration (mins)').and('contain', 'Date').and('contain', 'Tags').and('contain', 'Actions');
    })*/
    it('User click on Add New Assessment ,User is navigated to Assessment add page ', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/assessment/manage"]').click()
        cy.get('a:contains(Add New Assessment)').click()
        cy.contains('LMS').should('exist')
        cy.contains('Assessment').should('exist')
        cy.contains('Add').should('exist')
        cy.get('button:contains(Save)').should('be.disabled').should('exist')
        cy.get('div[class="panel-heading"]').children('span:contains(Assessment)').should('be.visible').next().find('input[type="checkbox"]').should('exist').parent().next().children('label:contains(Tags)').should('be.visible').next().find('button[class="dropdown-toggle"]').should('exist')
    })/*
    it('User should drage the questions published on LMS-Manage page preview the questions dragged', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/assessment/manage"]').click()
        cy.contains('td', 'ABC').siblings('td').contains('Unit test').click()
        cy.get('input[placeholder="Search"]').type('what is your name?')
        cy.get('input[placeholder="Search"]').parent().siblings().children('i[class="fa fa-search"]').click()
        //cy.get('i[class="fa fa-search"]').click({ multiple: true })
        cy.contains('what is your name?').parents('.list-group-item').find('.fa.fa-exchange').click();
        cy.get('a:contains(Preview)').click()
    })*/
    it('Verify back button in content feature', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/curriculum"]').click({force: true})    
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/curriculum')  
        cy.click_Back_Button({force: true})   
        cy.url().should('eq', Cypress.config().baseUrl + '/lms')                         
      })
      it('Verify back button in QA feature', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/qa/add"]').click()    
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/qa/add')  
        cy.click_Back_Button()  
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/qa') 
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/lms')  
        cy.get('a[href="/ctng4/lms/qa"]').click() 
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/qa') 
        cy.get('button:contains(Add Question)').click()  
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/qa/add') 
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/qa')
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/lms')                         
      })
      it('Verify back button in Assessment Setup feature', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/assessment/add"]').click()    
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/assessment/add')  
        cy.click_Back_Button()  
        cy.url().should('eq', Cypress.config().baseUrl + '/lms') 
        cy.get('a[href="/ctng4/lms/assessment/manage"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/assessment/manage') 
        cy.get('a:contains(Add New Assessment)').click() 
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/assessment/add')  
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/lms')  
        cy.get('a[href="/ctng4/lms/assessment/manage"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/assessment/manage')
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/lms')                         
      })
      it('Verify back button in Assessment feature', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/assessment/taking"]').click()    
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/assessment/taking')  
        cy.click_Back_Button()  
        cy.url().should('eq', Cypress.config().baseUrl + '/lms')                          
      })
      it('Verify back button in Study feature', () => {
        cy.visit('/lms')
        cy.get('a[href="/ctng4/lms/curriculum/study"]').click()    
        cy.url().should('eq', Cypress.config().baseUrl + '/lms/curriculum/study')  
        cy.click_Back_Button()  
        cy.url().should('eq', Cypress.config().baseUrl + '/lms')                          
      })
})