describe('Receipt feature Test', () => {
    const un = Cypress.env('USERNAME')
    const pwd = Cypress.env('PASSWORD')
    beforeEach(() => {
        cy.receipt_login(un, pwd)
    })
    it('when user click on receipts link,should navigate to receipts page successfully ', () => {
        cy.visit('/receipts')
        cy.url().should('include', '/receipts')
        cy.contains('Monthwise Receipt Collection').should('be.visible')
        cy.get('a[href="/ctng4/receipts/detailedReport"]').should('exist')
        cy.get('a[href="/ctng4/receipts/revenueSharingReport"]').should('exist')
        cy.get('a[href="/ctng4/receipts/receiptsSummaryReport"]').should('exist')
    })
    it('when user click on receipts add should navigate to receipts/add page successfully ', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/add"]').click()
        cy.url().should('include', '/receipts/add')
        cy.get('div.col-md-4').should('exist').contains('Receipt Type : ').siblings('span').should('contain', 'Regular').should('contain', 'Donation').find('input[value="Regular"]').should('exist').should('be.checked').next().should('exist').should('not.be.checked').check().should('be.checked')
        cy.get('div.col-md-4').should('exist').contains('Customer Type : ').siblings('span').should('contain', 'Regular').should('contain', ' Student ').find('input[value="Regular"]').should('exist').should('be.checked').next().should('exist').should('not.be.checked').check().should('be.checked')
        cy.get('div.col-md-4').find('input[value="Regular"]').check()
        cy.get('label[for="receiptDate"]').should('be.visible') // verify that it's visible
        cy.get('input[name="receiptDate"]').should('be.visible').click() // click on the element
        cy.get('.bs-datepicker-container').should('be.visible')
        cy.get('input[name="custName"]').should('exist')
        cy.get('textarea[name="custAddress"]').should('exist')
        cy.get('textarea[name="custContact"]').should('exist')
        cy.get('input[type="checkbox"]').should('be.visible')
        cy.get('span').contains('Revenue Sharing').should('be.visible')
    })/*
    it('when user click on Receipt search should navigate to Receipt manage page successfully ', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/manage"]').click()
        cy.url().should('include', 'receipts/manage')
        cy.get('input[placeholder="Search by: name, receipt number or date (yyyy-mm-dd)"]').should('exist')
        cy.get('a:contains(Add New Receipt)').should('exist')
        cy.get('table[class="table table-bordered table-striped"]').children('thead').children('tr').each((index, element) => {
            const expectedHeader = ['Date', 'Receipt No', 'Issued To', 'Amount', 'Payment Mode', 'Actions']
            expect(element.textContent).to.equal(expectedHeader[index])
        })
    })
    it('when user click on Add New Receipt, should navigate to receipts/add page successfully ', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/manage"]').click()
        cy.get('a:contains(Add New Receipt)').click()
        cy.url().should('include', '/receipts/add')
        cy.get('div.col-md-4').should('exist').contains('Receipt Type : ').siblings('span').should('contain', 'Regular').should('contain', 'Donation').find('input[value="Regular"]').should('exist').should('be.checked').next().should('exist').should('not.be.checked').check().should('be.checked')
        cy.get('div.col-md-4').should('exist').contains('Customer Type : ').siblings('span').should('contain', 'Regular').should('contain', ' Student ').find('input[value="Regular"]').should('exist').should('be.checked').next().should('exist').should('not.be.checked').check().should('be.checked')
        cy.get('div.col-md-4').find('input[value="Regular"]').check()
        cy.get('label[for="receiptDate"]').should('be.visible')
        cy.get('input[name="receiptDate"]').should('be.visible').click()
        cy.get('.bs-datepicker-container').should('be.visible')
        cy.get('input[name="custName"]').should('exist')
        cy.get('textarea[name="custAddress"]').should('exist')
        cy.get('textarea[name="custContact"]').should('exist')
        cy.get('input[type="checkbox"]').should('be.visible')
        cy.get('span').contains('Revenue Sharing').should('be.visible')
    })
    it('when user click on print icon,user should be dircted to print page', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/manage"]').click()
        cy.url().should('include', 'receipts/manage')
        cy.contains('tr td', Cypress.env('Recepiet')).parent().find('td.text-center:first-of-type span[title="Print"] a').should('be.visible')
    })
    it('when user click on Cancel Receipt icon, selected receipt should get disabled', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/manage"]').click()
        cy.url().should('include', 'receipts/manage')
        cy.get('input[type="search"]').type(Cypress.env('Recepiet')).parent().next().children('i[class="fa fa-search"]').click()
        cy.contains('tr td', Cypress.env('Recepiet')).parent().find('span[title="Cancel Receipt"]').click()
        cy.contains('tr td', Cypress.env('Recepiet')).parent().find('span[title="Enable Receipt"]').click()
    })
    it('when user enter all valid details in textfield Generate button should get enabled and when click on it, Recipt should display with details ', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/add"]').click()
        cy.get('input[name="custName"]').type(Cypress.env('custName'))
        cy.get('textarea[name="custAddress"]').type(Cypress.env('custAddress'))
        cy.get('textarea[name="custContact"]').type(Cypress.env('custContact'))
        cy.get('a[style="cursor:pointer"]').click()
        cy.get('input[name="particular"]').type('Exam Fee')
        cy.get('input[name="amount"]').type('1500')
        cy.get('button:contains(Save)').click()
        cy.get('button:contains(Generate)').click()
        cy.contains('div.panel-heading', 'Receipt').should('be.visible')
        cy.get('a:contains(Print)').should('be.visible')
    })
    it('when user select  Donation ,  Donation option should get selected', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/add"]').click()
        cy.get('input[value="Donation"]').check()
        cy.get('label[for="receiptDate"]').should('be.visible')
        cy.get('input[name="receiptDate"]').should('be.visible').click()
        cy.get('.bs-datepicker-container').should('be.visible')
        cy.get('input[name="custName"]').should('exist')
        cy.get('textarea[name="custAddress"]').should('exist')
        cy.get('textarea[name="custContact"]').should('exist')
        cy.get('input[type="checkbox"]').should('be.visible')
        cy.get('span').contains('80G Exemption').should('be.visible')
    })
    it('when user select Student,Student option should get selected', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/add"]').click()
        //cy.get('div.col-md-4').find('input[value=" Student "]').check()
        cy.get('input[value="Student"]').check()
        cy.get('label[for="receiptDate"]').should('be.visible')
        cy.get('input[name="receiptDate"]').should('be.visible').click()
        cy.get('.bs-datepicker-container').should('be.visible')
        cy.get('input[name="custName"]').should('exist')
        cy.get('textarea[name="custAddress"]').should('exist')
        cy.get('textarea[name="custContact"]').should('exist')
        cy.get('input[type="checkbox"]').should('be.visible')
        cy.get('span').contains('Revenue Sharing').should('be.visible')
        cy.get('input[placeholder="Class"]').should('exist')
        cy.get('input[placeholder="Section"]').should('exist')
    })
    it('When user click on receipt number,should navigate to edit page', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/manage"]').click()
        cy.get('input[type="search"]').type(Cypress.env('Recepiet')).parent().next().children('i[class="fa fa-search"]').click()
        cy.contains('tr td', Cypress.env('Recepiet')).click()
        cy.url().should('include', '/receipts/edit')
        cy.get('a:contains(Receipts)').next().next('a').should('have.text', Cypress.env('Recepiet')).should('be.visible')
        cy.get('div:contains(Receipt )').should('be.visible').children().children('button:contains(Update)').should('be.visible').should('exist')
        cy.get('label:contains(Receipt Type : )').parent().siblings('span').should('contain', 'Regular').should('contain', 'Donation').find('input[value="Regular"]').should('exist').next().should('exist').should('not.be.checked')
        cy.get('label[for="receiptDate"]').should('be.visible')
        cy.get('input[name="receiptDate"]').should('be.visible').click()
        cy.get('.bs-datepicker-container').should('be.visible')
        cy.get('input[name="custName"]').should('exist')
        cy.get('textarea[name="custAddress"]').should('exist')
        cy.get('textarea[name="custContact"]').should('exist')
        cy.get('input[type="checkbox"]').should('be.visible')
        cy.get('span').contains('Revenue Sharing').should('be.visible')
        cy.get('div:contains(Payment Details )').should('be.visible').children().children('button:contains(Update)').should('be.visible').should('exist')
        cy.get('strong:contains(Payment Mode)').should('be.visible').parents('td').siblings().children('span').within(() => {
            cy.get('span:contains(Cash)').should('be.visible').prev('input[type="radio"]').should('exist')
            cy.get('span:contains(Cheque)').should('be.visible').prev('input[type="radio"]').should('exist')
            cy.get('span:contains(DD)').should('be.visible').prev('input[type="radio"]').should('exist')
            cy.get('span:contains(Netbanking)').should('be.visible').prev('input[type="radio"]').should('exist')
        })
    })
    it.only('when user click on Detailed report link should navigate to detailedReport page', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/detailedReport"]').click({force: true})
        cy.url().should('include', '/receipts/detailedReport')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('span:contains(Include Order Items)').should('be.visible').prev('input[type="checkbox"]').should('exist')
        cy.get('span:contains(Include Customer Address)').should('be.visible').prev('input[type="checkbox"]').should('exist')
        cy.get('label:contains(Range : )').next().children('select').should('be.visible').find('option').should('have.length', 5)
            .then((options) => {
                const optionValues = ['Daily', 'Monthly', 'Quarterly', 'Annual', 'Custom']
                options.each((i, option) => {
                    expect(option.text).to.equal(optionValues[i])
                })
            })
        cy.get('span:contains(Date :)').should('be.visible').next().children('input[name="reportDailyDate"]').should('exist')
        cy.click_Back_Button()
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts')
    })
    it.only('when user click on Revenue Sharing Report link should navigate to revenueSharingReport page', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/revenueSharingReport"]').click({force: true})
        cy.url().should('include', '/receipts/revenueSharingReport')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('label:contains(Range : )').should('be.visible').next().children('select').should('be.visible').find('option').should('have.length', 2)
            .then((options) => {
                const optionValues = ['Monthly', 'Annual']
                options.each((i, option) => {
                    expect(option.text).to.equal(optionValues[i])
                })
            })
        cy.get('label:contains(Grouping : )').should('be.visible').next().children('select[name="grouping"]').should('be.visible').find('option').should('have.length', 2)
            .then((options) => {
                const optionValues = ['person', 'class']
                options.each((i, option) => {
                    expect(option.value).to.equal(optionValues[i])
                })
            })
        cy.click_Back_Button()
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts')
    })
    it.only('When user select monthly option Revenue Sharing Report page, dropdown containing month options should dispaly', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/revenueSharingReport"]').click({force: true})
        cy.url().should('include', '/receipts/revenueSharingReport')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('label:contains(Range : )').should('be.visible').next().siblings().children('select').should('be.visible').find('option').should('have.length', 12)
            .then((options) => {
                const optionValues = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
                options.each((i, option) => {
                    expect(option.text).to.equal(optionValues[i])
                })
            })
        cy.click_Back_Button()
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts')
    })
    it.only('when user click on Summary Report link should navigate to receiptsSummaryReport page', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/receiptsSummaryReport"]').click({force: true})
        cy.url().should('include', '/receipts/receiptsSummaryReport')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('label:contains(Range : )').should('be.visible').next().children('select').should('be.visible').find('option').should('have.length', 5)
            .then((options) => {
                const optionValues = ['Daily', 'Monthly', 'Quarterly', 'Annual', 'Custom']
                options.each((i, option) => {
                    expect(option.text).to.equal(optionValues[i])
                })
            })
        cy.get('span:contains(Date :)').should('be.visible').next().children('input[name="reportDailyDate"]').should('exist')
        cy.click_Back_Button()
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts')
    })
    it.only('Verify back button in REcipts feature', () => {
        cy.visit('/receipts')
        cy.get('a[href="/ctng4/receipts/add"]').click({force: true})
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts/add')
        cy.click_Back_Button()
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts')
        cy.get('a[href="/receipts/manage"]').click({force: true})
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts/manage')
        cy.get('a:contains(Add New Receipt)').click({force: true})
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts/add')
        cy.click_Back_Button()
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts/manage')
        cy.get('th:contains(Receipt No)').parents('thead').next('tbody').children('tr').first().find('a:contains(126/BTLCOL)').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts/edit')
        cy.click_Back_Button()
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts/manage')
        cy.click_Back_Button()
        cy.url().should('eq', Cypress.config().baseUrl + '/receipts')
    })*/
})