import cypress = require("cypress")
let pendingAmount
describe('Fee feature Test', () => {
    const un = Cypress.env('USERNAME')
    const pwd = Cypress.env('PASSWORD')
    beforeEach(() => {
        cy.fee_login(un, pwd)
    })
    it('When user click on fee link user should navigate to fee page', () => {
        cy.visit('/fees')
        cy.url().should('include', '/fees')
        cy.get('a[href="/ctng4/fees/manage"]').should('exist')
        cy.get('a[href="/ctng4/fees/add"]').should('exist')
        cy.get('a[href="/ctng4/fees/transactions"').should('exist')
        cy.get('a[href="/ctng4/fees/transactions/add"]').should('exist')
        cy.get('a[href="/ctng4/fees/feesStructureReport"]').should('exist')
        cy.get('a[href="/ctng4/fees/coursewiseFeesStructureReport"]').should('exist')
        cy.get('a[href="/ctng4/fees/feesExpectedReport"]').should('exist')
    })
    it('When user click on fees add link user should navigate to fees/add page', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/add"]').click()
        cy.url().should('include', '/add')
        cy.get('input[placeholder="Name"]').should('exist')
        cy.get('input[placeholder="Display Text"]').should('exist')
        cy.get('select[name="collect"]').should('exist')
        cy.get('input[placeholder="Tags"]').should('exist')
    })
    it('When user click on Payment Schedule, should exist description, Amount and due date textfield', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/add"]').click()
        cy.get('strong:contains(Payment Schedule)').click()
        cy.get('input[placeholder="Description"]').should('exist')
        cy.get('input[placeholder="Amount"]').should('exist')
        cy.get('input[placeholder="Due Date"]').should('exist')
    })
    it('When user click on Fine, should exist description and Amounttextfield', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/add"]').click()
        cy.get('strong:contains(Fine)').click()
        cy.get('input[placeholder="Description"]').should('exist')
        cy.get('input[placeholder="Amount"]').should('exist')
    })
    it('When user click on transact add link, should navigate to transactions/add page', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/transactions/add"]').click()
        cy.url().should('include', '/fees/transactions/add')
        cy.get('input[placeholder="search"]').should('exist')
    })
    it('When user click on transact manage link, should navigate to transactions page', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/transactions"]').click()
        cy.url().should('include', '/fees/transactions')
        cy.get('input[type="search"]').should('exist')
        cy.get('a:contains(New Transaction)').should('exist')
    })
    it('When user click on New Transaction link, should navigate to transactions/add page', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/transactions"]').click()
        cy.get('a:contains(New Transaction)').click()
        cy.url().should('include', 'transactions/add')
        cy.get('input[type="search"]').should('exist')
    })/*
    it('When user click on disable link, selected transaction should get disabled', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/transactions"]').click()
        cy.get('input[placeholder="Search"]').type(Cypress.env('Recepiet')).parent().next().children('i[class="fa fa-search"]').click()
        //cy.get('i[class="fa fa-search"]').click()
        cy.get('thead[class="bg-info"]').next().find('tr').last().find('a[class="text-danger"]').click()
        //cy.contains('tr', 'Aadya Rao').contains('a', 'Disable').click()
        cy.get('thead[class="bg-info"]').next().find('tr').last().find('a[class="text-success"]').click()
        //cy.contains('tr', 'Aadya Rao').contains('a', 'Enable').click()
    })*/
    it('when user enter all valid details in all field fee add page and click on save button , fee details should get added and navigate to fee amnage', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/add"]').click()
        function getRandomItem(arr) {
            const randomIndex = Math.floor(Math.random() * arr.length);
            const item = arr[randomIndex];
            return item;
        }
        const array = ['Admission fee', 'Computer Fees', 'New Admission', 'Tuition Fees', 'Exam Fee', 'Lab Fee', 'Sports Fee', 'miscellaneous', 'term Fee', 'Exam registration fee']
        const string = getRandomItem(array)
        cy.get('input[placeholder="Name"]').type(string)
        const str = getRandomItem(array)
        cy.get('input[placeholder="Display Text"]').type(str)
        //cy.get('strong:contains(Paid By Students)').click()
        cy.get('span:contains(FInance)').parent().siblings('input[type="checkbox"]').check()
        cy.get('strong:contains(Payment Schedule)').click()
        cy.get('input[placeholder="Description"]').type(string)
        cy.get('input[placeholder="Amount"]').type('500')
        cy.get('button:contains(Save)').click()
        // cy.url().should('include', '/fees/manage')
        // cy.contains('tr',str).within(() => {cy.contains('button',string) .should('exist') })
        //cy.get('th:contains( Display Text )').parent().parent().siblings().find('tr').contains(string).should('exist')
        //cy.get('tr').contains(string).should('exist')
        //cy.contains('tr', string).should('exist')
    })
    it('When user click on fees Manage link user should navigate to fees/manage page', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/manage"]').click()
        cy.url().should('include', '/fees/manage')
        cy.get('input[placeholder="Search"]').should('exist')
        cy.get('button:contains(Add Fee)').should('be.visible')
    })
    it('When user click on Add Fee button, user should navigate to fees/add page', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/manage"]').click()
        cy.get('button:contains(Add Fee)').click()
        cy.url().should('include', '/add')
        cy.get('input[placeholder="Name"]').should('exist')
        cy.get('input[placeholder="Display Text"]').should('exist')
        cy.get('select[name="collect"]').should('exist')
        cy.get('input[placeholder="Tags"]').should('exist')
    })/*
    it('When user click on fee name, user should navigate to fees/edit page', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/manage"]').click()
        cy.contains('tr', 'fees').within(() => { cy.contains('button', 'admission pcmb').click() })
        cy.get('input[placeholder="Name"]').should('exist')
        cy.get('input[placeholder="Display Text"]').should('exist')
        cy.get('select[name="collect"]').should('exist')
        cy.get('input[placeholder="Tags"]').should('exist')
        cy.get('button:contains(Save)').should('be.enabled').should('exist')
        cy.get('strong:contains(Payment Schedule)').should('exist')
        cy.get('strong:contains(Fine)').should('exist')
    })
    it('When user click on Disable link, selected fee should get disable', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/manage"]').click()
        cy.contains('tr', 'fees').within(() => { cy.get('a[title="Disable Fee"]').click() })
        cy.contains('tr', 'fees').within(() => { cy.get('a[title="Enable Fee"]').click() })
    })
    it('When user click Receipt number, should navigate to transactions/edit page', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/transactions"]').click()
        cy.get('input[placeholder="Search"]').clear().type(Cypress.env('Recepiet'))
        cy.get('i[class="fa fa-search"]').click()
        cy.get('tr').contains('1/BTLCOL').click()
        cy.url().should('include', '/fees/transactions/edit')
        cy.get('div:contains(Fee transactions cannot be edited. If this feature is required please contact )').should('be.visible')
        cy.get('a:contains(support@campustrack.net)').should('exist')
        cy.get('strong').should('contain', Cypress.env('Recepiet')).should('be.visible')
    })
   
    it('When user enter student details in textfield and search, resepected student Tranctions details should display', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/transactions/add"]').click()
        cy.url().should('include', 'transactions/add')
        cy.get('input[type="search"]').type(Cypress.env('studentName')).next().children('ul').click()
        cy.get('strong:contains(Receipt No : #)').should('be.visible').parent().next().children().find('input[name="date"]').should('exist')
        cy.get('strong:contains(Receipt No : #)').should('be.visible').parent().next().next('button:contains(Save)').should('be.disabled').should('exist')
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').parents('td').next().children('select').should('exist').find('option').should('have.length', 4)
            .then((options) => {
                const optionValues = ['- Select Mode -', 'cash', 'cheque', 'online']
                options.each((i, option) => {
                    expect(option.text).to.equal(optionValues[i]) // Verify that the option values match the expected values
                })
            })
        cy.get('label:contains(Adjustment Amt )').should('be.visible').prev('input[type="checkbox"]').should('exist')
        cy.get('strong:contains(Total)').should('be.visible')
        cy.get('button:contains(Save)').should('be.disabled')
    })
    it('When user enter amount in Amount received Textfield and select payment mode and select pending fees if amount recived and total amount is equal ,then only save button should get enabled', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/transactions/add"]').click()
        cy.url().should('include', 'transactions/add')
        cy.get('input[type="search"]').type(Cypress.env('studentName')).next().children('ul').click()
        const recived_amount = Cypress.env('value').toString()
        // const recived_amount = amount.toString()
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').type(recived_amount)
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').parents('td').next().children('select').select('Cash')
        cy.get('div[class="tab-content"]').children().next().children().find('tbody tr').first().as('firstRow')
        cy.get('@firstRow').find('input[type="checkbox"]').check()
        // cy.get('div[class="tab-content"]').children().next().children().find('tbody').children().find('input[type="checkbox"]').click()
       // cy.get('td:contains(Tuition Fee July 2020 )').next().next().children('input[type="checkbox"]').check()
        cy.get('td.text-right strong').invoke('text').then(total => {
            const totalAmount = total.replace(/₹|,/g, '') // remove the ₹ symbol and comma
            expect(totalAmount).to.equal(Cypress.env('value')) // assert that the total amount is equal to recived amount
            cy.log('Recived amount and Total amount are equal')
        })
        cy.get('button:contains(Save)').should('be.enabled').should('exist').and('be.visible')
    })
    it('check weather  Adjustment Amt checkbox is get enabled if the amount received is greater than the total pending fees', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/transactions/add"]').click()
        cy.get('input[type="search"]').type(Cypress.env('studentName')).next().children('ul').click()
        cy.get('div[class="tab-content"]').children().next().children().find('tbody').last().find('strong').invoke('text').then(total => {
            pendingAmount = total.replace(/[₹,]|Total/g, '')
        })
        const recived_amount = parseInt(pendingAmount) + parseInt(Cypress.env('value'))
        const amount = recived_amount.toString()
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').type(amount)
        cy.get('label:contains(Adjustment Amt )').should('be.visible').prev('input[type="checkbox"]').should('be.enabled').should('exist').check().should('be.checked')
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').parents('td').next().children('select').select('Cash')
        cy.get('div[class="tab-content"]').children().next().children().find('tbody tr').first().as('firstRow')
        cy.get('@firstRow').find('input[type="checkbox"]').check()
        //cy.get('div[class="tab-content"]').children().next().children().find('tbody').first().find('input[type="checkbox"]').check()
        //cy.get('td:contains(Tuition Fee July 2020 )').next().next().children('input[type="checkbox"]').check()
        cy.get('button:contains(Save)').should('be.enabled').should('exist').and('be.visible')
    })
    it('check weather Adjustment Amt checkbox is disabled if the amount received is less than the total pending fees', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/transactions/add"]').click()
        cy.get('input[type="search"]').type(Cypress.env('studentName')).next().children('ul').click()
        cy.get('div[class="tab-content"]').children().next().children().find('tbody').last().find('strong').invoke('text').then(total => {
            pendingAmount = total.replace(/[₹,]|Total/g, '')
        })
        var recived_amount
        var amount
        if (parseInt(pendingAmount) > parseInt(Cypress.env('value'))) {
            amount = Cypress.env('value')
        } else if (parseInt(pendingAmount) < parseInt(Cypress.env('value'))) {
            recived_amount = parseInt(Cypress.env('value')) - parseInt(pendingAmount)
            amount = recived_amount.toString()
        } else {
            amount = Cypress.env('value')
        }
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').type(amount)
        cy.get('label:contains(Adjustment Amt )').should('be.visible').prev('input[type="checkbox"]').should('be.disabled').should('exist').should('not.be.checked')
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').parents('td').next().children('select').select('Cash')
        cy.get('div[class="tab-content"]').children().next().children().find('tbody tr').first().as('firstRow')
        cy.get('@firstRow').find('input[type="checkbox"]').check()
        //cy.get('div[class="tab-content"]').children().next().children().find('tbody').first().find('input[type="checkbox"]').check()
        //cy.get('td:contains(Tuition Fee July 2020 )').next().next().children('input[type="checkbox"]').check()
        cy.get('button:contains(Save)').should('be.enabled').should('exist').and('be.visible')
    })
    it('When user enter recived amount and select required option and click on save button,should redirected to the search text field in the TransactionsAdd page', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/transactions/add"]').click()
        cy.get('input[type="search"]').type(Cypress.env('studentName')).next().children('ul').click()
        cy.get('div[class="tab-content"]').children().next().children().find('tbody').last().find('strong').invoke('text').then(total => {
            pendingAmount = total.replace(/[₹,]|Total/g, '')
        })
        var recived_amount
        var amount
        if (parseInt(pendingAmount) > parseInt(Cypress.env('value'))) {
            amount = Cypress.env('value')
        } else if (parseInt(pendingAmount) < parseInt(Cypress.env('value'))) {
            amount = Cypress.env('value')
            cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').type(amount)
            cy.get('label:contains(Adjustment Amt )').should('be.visible').prev('input[type="checkbox"]').check()
        } else {
            amount = Cypress.env('value')
        }
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').type(amount)
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').parents('td').next().children('select').select('Cash')
        cy.get('div[class="tab-content"]').children().next().children().find('tbody tr').first().as('firstRow')
        cy.get('@firstRow').find('input[type="checkbox"]').check()
        //cy.get('div[class="tab-content"]').children().next().children().find('tbody').first().find('input[type="checkbox"]').check()
        //cy.get('td:contains(Tuition Fee July 2020 )').next().next().children('input[type="checkbox"]').check()
        cy.get('button:contains(Save)').click()
        cy.url().should('include', '/fees/transactions/add')
    })
    it('When recived amount is more than total pending fee, if user not select Adjustment Amt then save should not be enabled', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/transactions/add"]').click()
        cy.get('input[type="search"]').type(Cypress.env('studentName')).next().children('ul').click()
        cy.get('div[class="tab-content"]').children().next().children().find('tbody').last().find('strong').invoke('text').then(total => {
            pendingAmount = total.replace(/[₹,]|Total/g, '')
        })
        var recived_amount
        var amount
        if (parseInt(pendingAmount) > parseInt(Cypress.env('value'))) {
            recived_amount = parseInt(pendingAmount) + parseInt(Cypress.env('value'))
            amount = recived_amount.toString()
        } else if (parseInt(pendingAmount) < parseInt(Cypress.env('value'))) {
            amount = Cypress.env('value')
        } else {
            amount = Cypress.env('value')
        }
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').type(amount)
        cy.get('label:contains(Adjustment Amt )').should('be.visible').prev('input[type="checkbox"]').should('be.enabled').should('not.be.checked')
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').parents('td').next().children('select').select('Cash')
        cy.get('div[class="tab-content"]').children().next().children().find('tbody tr').first().as('firstRow')
        cy.get('@firstRow').find('input[type="checkbox"]').check()
       // cy.get('div[class="tab-content"]').children().next().children().find('tbody').first().find('input[type="checkbox"]').check()
       // cy.get('td:contains(Tuition Fee July 2020 )').next().next().children('input[type="checkbox"]').check()
        cy.get('button:contains(Save)').should('be.disabled').should('be.visible')
    })
    it('When user enter amount recived ,if not selected any of pending fees from avilable option then Save button should not enabled', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/transactions/add"]').click()
        cy.url().should('include', 'transactions/add')
        cy.get('input[type="search"]').type(Cypress.env('studentName')).next().children('ul').click()
        const recived_amount = Cypress.env('value').toString()
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').type(recived_amount)
        cy.get('span:contains(Amount received)').parent().next().find('input[type="text"]').parents('td').next().children('select').select('Cash')
        cy.get('button:contains(Save)').should('be.disabled').should('exist').and('be.visible')
    })
    it('When user click on Fees paid tab ,paid fees reciept details should display', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/transactions/add"]').click()
        cy.url().should('include', 'transactions/add')
        cy.get('input[type="search"]').type(Cypress.env('studentName')).next().children('ul').click()
        cy.get('tabset[class="tab-container"]').children('ul[class="nav nav-tabs"]').first().find('span:contains(Fees Paid)').click()
        cy.get('label:contains(Summary)').should('be.visible').prev('input[type="radio"]').should('be.checked').should('exist')
        cy.get('label:contains(Detail)').should('be.visible').prev('input[type="radio"]').should('not.be.checked').should('exist')
        cy.get('label:contains(Adj Fees)').should('be.visible').prev('input[type="radio"]').should('not.be.checked').should('exist')
    })
    it('When user click on datepicker, calender should dispaly', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/transactions/add"]').click()
        cy.url().should('include', 'transactions/add')
        cy.get('input[type="search"]').type(Cypress.env('studentName')).next().children('ul').click()
        cy.get('[name="date"]').click()
        cy.get('div[class="bs-calendar-container"]').should('be.visible')
    })
    it('when user click on Adjustment Balance link, should navigate to Adjustment Balance Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/fees/adjustmentBalanceReport"]').click()
        cy.url().should('contain', '/fees/adjustmentBalanceReport')
        cy.get('h3').should('contain.text', 'FeesAdjustment Balance Report')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('span:contains(Course : )').should('be.visible').next('select').select('PUC I PCME')
        cy.get('i[class="fa fa-print"]').click()
    })*/
    it('when user click on Adjustment Balance link, should navigate to Adjustment Balance Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/adjustmentBalanceReport"]').click()
        cy.url().should('contain', '/fees/adjustmentBalanceReport')
        cy.get('h3').should('contain.text', 'FeesAdjustment Balance Report')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('span:contains(Course : )').should('be.visible').next('select').select('PUC I PCMB')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').click()
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Fees Structure link, should navigate to Fees Structure Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/feesStructureReport"]').click()
        cy.url().should('contain', '/feesStructureReport')
        cy.get('h3').should('contain.text', 'Fees Fees Structure Report')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').click()
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Fees Structure Coursewise link, should navigate to Fees Structure Coursewise  Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/coursewiseFeesStructureReport"]').click({force: true})
        cy.url().should('contain', '/coursewiseFeesStructureReport')
        cy.get('h3').should('contain.text', 'FeesCoursewise Fees Structure Report')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').should('exist')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Fees Fees Expected link, should navigate to Fees Expected Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/feesExpectedReport"]').click()
        cy.url().should('contain', '/feesExpectedReport')
        cy.get('h3').should('contain.text', 'Fees Fees Expected')
        cy.get('span:contains( Default (no date check) )').next().children('span[class="dropdown-down"]').click()
        cy.get('div:contains(Monthly)').prev('input[type="checkbox"]').check({ force: true })
        cy.get('span:contains(--- Select Month ---)').next().find('span[class="dropdown-down"]').click({ force: true })
        cy.get('div:contains(Jan 2023)').prev('input[type="checkbox"]').check({ force: true })
        cy.get('span:contains(--- Select Fees ---)').next().find('span[class="dropdown-down"]').should('exist')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').click()
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Defaulters List link, should navigate to Defaulters List Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/feesDefaultersListReport"]').click()
        cy.url().should('contain', '/feesDefaultersListReport')
        cy.get('h3').should('contain.text', 'Fees Defaulters List Report')
        cy.get('span:contains(Course : )').should('be.visible').next('select').should('exist').select('PUC I PCMB')
        cy.get('span:contains(As on :)').should('be.visible').next().children('input[name="reportFromDate"]').should('exist')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').click()
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Adjustment Transaction link, should navigate to Adjustment Transaction Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/adjustmentTransactionReport"]').click()
        cy.wait(2000)
        cy.url().should('contain', '/adjustmentTransactionReport')
        cy.get('h3').should('contain.text', 'Fees Adjustment Transaction Report')
        cy.get('span:contains(Course : )').should('be.visible').next('select').should('exist').select('PUC I PCMB')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').click()
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Advance Balance link, should navigate to Advance Balance Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/advanceBalanceReport"]').click()
        cy.wait(2000)
        cy.url().should('contain', '/advanceBalanceReport')
        cy.get('h3').should('contain.text', 'Fees Advance Balance Report')
        cy.get('span[class="dropdown-btn"]').should('exist')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').click()
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Fee Collection Datewise / Monthwise link, should navigate to Fee Collection Datewise / Monthwise page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/feesCollectedReport"]').click()
        cy.wait(2000)
        cy.url().should('contain', '/feesCollectedReport')
        cy.get('h3').should('contain.text', 'Fees Fee Collection Datewise / Monthwise')
        cy.get('span:contains(From Date :)').should('be.visible').next().children('input[name="reportFromDate"]').clear().type(Cypress.env('DateFrom'))
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').should('exist')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Fees Paid After Academic Year link, should navigate to Fees Paid After Academic Year page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/feesPaidAfterAcadYearReport"]').click()
        cy.wait(2000)
        cy.url().should('contain', '/feesPaidAfterAcadYearReport')
        cy.get('h3').should('contain.text', 'Fees Fees Paid After Academic Year')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').should('exist')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Fees Paid By TC Students link, should navigate to Fees Paid By TC Students report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/feesPaidByTCStudentsReport"]').click()
        cy.wait(2000)
        cy.url().should('contain', '/feesPaidByTCStudentsReport')
        cy.get('h3').should('contain.text', 'Fees Fees Paid By TC Students')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').should('exist')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Fees Paid List link, should navigate to Fees Paid List Report Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/feesPaidReport"]').click()
        cy.url().should('contain', 'feesPaidReport')
        cy.get('h3').should('contain.text', 'Fees Fees Paid List Report')
        cy.get('span:contains( Default (no date check) )').next().children('span[class="dropdown-down"]').click()
        cy.get('div:contains(Monthly)').prev('input[type="checkbox"]').check({ force: true })
        cy.get('span:contains(--- Select Month ---)').next().find('span[class="dropdown-down"]').click({ force: true })
        cy.get('div:contains(Jan 2023)').prev('input[type="checkbox"]').check({ force: true })
        cy.get('span:contains(Course : )').should('be.visible').next('select').should('exist').select('PUC I PCMB')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').should('exist')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Receipt Transaction link, should navigate to Receipt Transaction Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/feesReceiptTransactionReport"]').click()
        cy.url().should('contain', '/feesReceiptTransactionReport')
        cy.get('h3').should('contain.text', 'Fees Receipt Transaction Report')
        cy.get('span:contains( Default (no date check) )').next().children('span[class="dropdown-down"]').click()
        cy.get('div:contains(Monthly)').prev('input[type="checkbox"]').check({ force: true })
        cy.get('span:contains(--- Select Month ---)').next().find('span[class="dropdown-down"]').click({ force: true })
        cy.get('div:contains(Jan 2023)').prev('input[type="checkbox"]').check({ force: true })
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.get('i[class="fa fa-print"]').should('exist')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('when user click on Transaction History link, should navigate to Receipt Transaction History Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/transactionHistoryReport"]').click()
        cy.url().should('contain', '/transactionHistoryReport')
        cy.get('h3').should('contain.text', 'Fees Transaction History Report')
        cy.get('strong:contains(Customize)').parent().next().children().children('button[title="Download As PDF"]').should('exist').should('be.visible').next('button[title="Print"]').should('exist').should('be.visible').should('be.enabled')
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
       // cy.get('i[class="fa fa-print"]').click()
    })
    it('when user click on Student Transaction link, should navigate to Student Transaction History Report page and able to download report ', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/studentTransactionReport"]').click()
        cy.url().should('contain', '/fees/studentTransactionReport')
        cy.get('h3').should('contain.text', 'Fees Studentwise Transaction Report')
        cy.get('input[placeholder="search"]').should('exist').prev('i[class="fa fa-search"]').should('exist')
        cy.get('span:contains(Fees : )').should('be.visible').next('select').should('exist')
        cy.get('i[class="fa fa-print"]').should('exist').screenshot()
        cy.get('button[title="Download As PDF"]').should('exist')
        cy.click_Back_Button() 
        cy.url().should('eq', Cypress.config().baseUrl + '/fees') 
    })
    it('Verify back button in Fees feature', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/add"]').click()    
        cy.url().should('eq', Cypress.config().baseUrl + '/fees/add')  
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/fees')  
        cy.get('a[href="/ctng4/fees/manage"]').click()  
        cy.url().should('eq', Cypress.config().baseUrl + '/fees/manage') 
        cy.get('button:contains(Add Fee)').click()                          
        cy.url().should('eq', Cypress.config().baseUrl + '/fees/add')  
        cy.click_Back_Button()    
        cy.url().should('eq', Cypress.config().baseUrl + '/fees/manage') 
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/fees')                       
      })
      it('Verify back button in Transact feature', () => {
        cy.visit('/fees')
        cy.get('a[href="/ctng4/fees/transactions/add"]').click()    
        cy.url().should('eq', Cypress.config().baseUrl + '/fees/transactions/add')  
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/fees')  
        cy.get('a[href="/ctng4/fees/transactions"]').click()  
        cy.url().should('eq', Cypress.config().baseUrl + '/fees/transactions') 
        cy.get('a:contains(New Transaction)').click()                          
        cy.url().should('eq', Cypress.config().baseUrl + '/fees/transactions/add')  
        cy.click_Back_Button()    
        cy.url().should('eq', Cypress.config().baseUrl + '/fees/transactions') 
        cy.click_Back_Button()   
        cy.url().should('eq', Cypress.config().baseUrl + '/fees')                       
      })
})