
context('Primary feature test', () => {
    beforeEach(() => {
        cy.visit('/')
    })
    it('When User click on primary link should navigate to Primary page ', () => {
        cy.get('a[href="/primary"]').first().click()
        cy.url().should('eq', Cypress.config().baseUrl + '/primary')
        cy.get('ul').should('be.visible')
        const expectedTexts = ["Academics", "Infrastructure", "Extra-Curricular Activities", "Competitions", "Holistic Development", "Assessments"]
        cy.get("ul.dropdown-menu.sub-menu.show li").each((liElement, index) => {
            const liText = liElement.text().trim()
            expect(liText).to.equal(expectedTexts[index])
        })
        cy.contains('h4', 'Academics').should('be.visible')
            .next('p').should('have.text', 'The V.V.S.G.C.School is a co-education institution with English as the medium of instruction. The school follows the Karnataka State Board System which has been upgraded recently to the National Curriculum. The institution uses the standard books recommended by the DPI of the State Government. Additional books and reading material are utilized along with technology for enhanced learning.').should('be.visible')
            .next('p').should('have.text', 'Our institution aims at providing contemporary knowledge and skills to students through creative and innovative methods that stimulate thinking and motivate them to develop into well-moulded, responsible personalities. Our focus is on conceptual learning through a mix of both traditional chalk and talk and modern methods of teaching using technology, project work, dramatization and hands-on experience.').should('be.visible')
            .next('p').should('have.text', 'Technology offers unlimited new ways of teaching and learning.').should('be.visible')
        cy.contains('div', ' © 2023 V.V.S.G.C School. All Rights Reserved').should('be.visible')
    })
    it('When User click on Our Academics link , should navigte to Our Academics page ', () => {
        cy.get('a[href="/primary"]').first().click()
        cy.get('a[href="/primary/academics"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/primary/academics')
        cy.contains('h4', 'Academics').should('be.visible')
            .next('p').should('have.text', 'The V.V.S.G.C.School is a co-education institution with English as the medium of instruction. The school follows the Karnataka State Board System which has been upgraded recently to the National Curriculum. The institution uses the standard books recommended by the DPI of the State Government. Additional books and reading material are utilized along with technology for enhanced learning.').should('be.visible')
            .next('p').should('have.text', 'Our institution aims at providing contemporary knowledge and skills to students through creative and innovative methods that stimulate thinking and motivate them to develop into well-moulded, responsible personalities. Our focus is on conceptual learning through a mix of both traditional chalk and talk and modern methods of teaching using technology, project work, dramatization and hands-on experience.').should('be.visible')
            .next('p').should('have.text', 'Technology offers unlimited new ways of teaching and learning.').should('be.visible')
    })
    it('When User click on Infrastructure link , should navigte to Infrastructure page ', () => {
        cy.get('a[href="/primary"]').first().click()
        cy.get('a[href="/primary/infrastructure"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/primary/infrastructure')
        cy.contains('h4', 'Infrastructure').should('be.visible')
            .next('p').should('have.text', 'Spacious, bright, well-ventilated classrooms equipped with ergonomically designed furniture for students, bulletin boards, black boards, and Smart boards – form the essential feature of every classroom.').should('be.visible')
        cy.contains('h4', 'Library').should('be.visible')
            .next('p').should('have.text', 'A well-stocked and digitalised library consisting of over 15,000 books serves as a vast knowledge source for students and teachers. Books, journals, periodicals, magazines, fiction and non-fiction and encyclopedias form the library.\nStudents are encouraged to make active use of the library resources in their day-to-day learning. It is open to the students and staff on all school days.').should('be.visible')
        cy.contains('h4', 'Science Lab ').should('be.visible')
            .next('p').should('have.text', 'Provides ample space for learning science through experimentation.').should('be.visible')
        cy.contains('h4', 'Computer Lab ').should('be.visible')
            .next('p').should('have.text', 'A full-fledged computer laboratory where each student has access to individual computer, guided by well-qualified faculty.').should('be.visible')
        cy.contains('h4', 'Audio Visual Room ').should('be.visible')
            .next('p').should('have.text', 'The school boasts of a state of the art 60-seater AV room. Here students and teachers have a number of lecture sessions or audio-visual presentations.').should('be.visible')
        cy.contains('h4', 'Arogyadhama').should('be.visible')
            .next('p').should('have.text', 'Arogyadhama, a Health Centre with an experienced doctor to attend to the health needs of students and teachers. Annual health checkup is carried out for all the students.').should('be.visible')
        cy.contains('h4', 'Technology Support ').should('be.visible')
            .next('p').should('have.text', 'Smart Boards and Overhead projectors for all classes, K-yan, Galaxy Tabs, Smart LED Projector, Computers, Laptops, Digital Camera and Public address system to name a few. ').should('be.visible')
    })
    it('When User click on Extra-Curricular Activities link , should navigte to Extra-Curricular Activities page ', () => {
        cy.get('a[href="/primary"]').first().click()
        cy.get('a[href="/primary/extraCurricularActivities"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/primary/extraCurricularActivities')
        cy.contains('h4', 'Extra-Curricular Activities').should('be.visible')
            .next('h4').should('have.text', 'Physical Education').should('be.visible')
            .next('p').should('have.text', 'In addition to focusing on academic excellence, due importance is given to physical training and games. Regular PT classes are conducted as part of the schedule. Students get intense training to play organized games and they are encouraged to compete at the School, District, State and National level. The events include Cricket, Table Tennis, Shuttle Badminton, Volley ball, Throw ball and Athletics.').should('be.visible')
        cy.contains('h4', 'Art, Craft and Music ').should('be.visible')
            .next('p').should('have.text', 'To draw out the hidden talents in students, the school has well-designed programs. Competitions are organized to showcase their talents.').should('be.visible')
            .next('p').should('have.text', 'Music classes, conducted in the Music room are a part of the time-table. Students are trained to participate in music competitions conducted by various organizations.').should('be.visible')
    })
    it('When User click on Competitions link , should navigte to Competitions page ', () => {
        cy.get('a[href="/primary"]').first().click()
        cy.get('a[href="/primary/competitions"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/primary/competitions')
        cy.contains('h4', 'Competitions').should('be.visible')
            .next('p').should('have.text', 'To enhance literary skills and powers of expression, the following competitions are conducted. A few are :').should('be.visible')
            .next('h4').should('have.text', 'Literary ').should('be.visible')
            .next('p').should('have.text', 'Debate, Recitation, Essay writing, Picture description, Cross-word puzzle, etc.').should('be.visible')
            .next('h4').should('have.text', 'Cultural').should('be.visible')
            .next('p').should('have.text', 'To keep up our culture and tradition, literature and art-form, the following competitions are conducted every year. Group Song, Group Dance, Dramatics, Solo song and dance, Rangoli, Cookery, Mehandi designing to name a few.').should('be.visible').next()
            .next('h4').should('have.text', 'Competitive Exams').should('be.visible')
            .next('p').should('have.text', 'To help students think differently, improve their application skills and prepare them for advanced learning they are motivated to take up competitive exams conducted by various National and International Organisations viz.').should('be.visible')
            .next('ul').children('li').each((item, index) => {
                const expectedTexts = ['All India General Knowledge Exam', 'Math and Science Olympiad', 'Diagnostic test conducted by ASSET (Educational Initiatives)', 'IA&AS']
                cy.contains('li', expectedTexts[index])
            })
    })
    it('When User click on Holistic Development link , should navigte to Holistic Development page ', () => {
        cy.get('a[href="/primary"]').first().click()
        cy.get('a[href="/primary/holisticDevelopment"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/primary/holisticDevelopment')
        cy.contains('h4', 'Holistic Development').should('be.visible')
            .next('h4').should('have.text', 'World Literary Day / Reading Day').should('be.visible')
            .next('p').should('have.text', 'Conducted on the last Friday of November every year.').should('be.visible')
            .next('ul').children('li').each((item, index) => {
                const expectedTexts = ['“One Nation Reading together.”', '“Words are the root of everything. When we read books, we begin to exist.”', '“If there were no words, how could we even think?”']
                cy.contains('li', expectedTexts[index])
            })
        cy.contains('h4', 'World Environment Day ').should('be.visible')
            .next('p').should('have.text', 'Celebrated on 5th June every year. Students prepare charts, slogans and write-ups on the topic.').should('be.visible')
        cy.contains('h4', 'Focus on our culture').should('be.visible')
            .next('p').should('have.text', 'To imbibe our culture, Bhagavadgita, Vishnusahasranama, Bhajagovindam, Hanuman Chalisa, Bhajans and Shlokas are recited by our students.').should('be.visible')
            .next('p').should('have.text', 'To inculcate noble values in students we have Spiritual Education Programme wherein resource persons are invited to address the students on value based education.').should('be.visible')
        cy.contains('h4', 'Language Development Programme').should('be.visible')
            .next('p').should('have.text', 'To inculcate reading habit and enhance language ability Newspapers (Student edition) from Times of India subscribed for students. A period per class is allotted every week. A resource person from NIE (News paper in Education) conducts various activities to improve linguistic skills in students.').should('be.visible')
    })
    it('When User click on Assessments link , should navigte to Assessments page ', () => {
        cy.get('a[href="/primary"]').first().click()
        cy.get('a[href="/primary/assessments"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/primary/assessments')
        cy.contains('h4', 'Assessments').should('be.visible')
            .next('p').should('have.text', 'Children are subjected to monthly reviews based on the topics covered during the course of the month. A comprehensive evaluation is presented to the parent. By the end of the year, these monthly reviews help in judging the overall performance of the child.').should('be.visible')
    })

})