
context('School feature test', () => {
    beforeEach(() => {
        cy.visit('/')
    })
    it('When User click on The School link should navigate to school page ', () => {
        cy.get('a[href="/school"]').first().click()
        cy.url().should('eq', Cypress.config().baseUrl + '/school')
        cy.get('ul').should('be.visible')
        const expectedTexts = ["Teaching Fraternity", "School Schedule", "Train The Teacher", "Achievements", "News"]
        cy.get("ul.dropdown-menu.sub-menu.show li").each((liElement, index) => {
            const liText = liElement.text().trim();
            expect(liText).to.equal(expectedTexts[index])
            cy.contains('a', 'VVS Gandhi Centenary English Primary School ').should('be.visible')
            cy.contains('a', 'About').should('be.visible')
        })
        cy.contains('div', ' © 2023 V.V.S.G.C School. All Rights Reserved').should('be.visible')
        cy.contains('h4', ' From the desk of Principal ').should('be.visible')
            .next('p').should('have.text', 'Changing school system demands clarity of thought, a certain amount of risk taking, a thorough knowledge and belief in what we wish to accomplish and a systematic approach to achieving those goals.').should('be.visible')
            .next('p').should('have.text', 'Technology is being used in ways that will help students reap rich dividends. It creates a learning environment that is vibrant and at the same time friendly. The school offers a host of interesting and exciting programs to raise teaching – learning standards.').should('be.visible')
            .next('p').should('have.text', 'Thus, with all this supports we lead our students to acquire personal developments and accomplishment. Embedded in the vision are our culture, beliefs, values, purposes and goals that serve as the mettle of this temple of learning developed on the watchword:“In pursuit of Excellence in Quality Education”').should('be.visible')
        cy.contains('h4', ' From the desk of Principal ').parent('div').prev('div').children("img").should("exist").and("have.attr", "src", "assets/img/Principal.jpg").next().children('strong:contains(Principal: Smt. Gita Venkatesh)').should('be.visible')
        cy.get(".col-md-3.staffCol").first().find("img").should("exist").and("have.attr", "src", "assets/img/Padmaja-HM-Playhome.jpg").next('div:contains(Smt Padmaja M N )').should('be.visible')
        cy.get(".col-md-3.staffCol").first().next().find("img").should("exist").and("have.attr", "src", "assets/img/Vani-HM-Nursery.jpg").next('div:contains(Smt Vani Sridhar B S )').should('be.visible')
        cy.get(".col-md-3.staffCol").first().next().next().find("img").should("exist").and("have.attr", "src", "assets/img/Kanaka-HM-HigerPrimary.jpg ").next('div:contains( Smt Kanaka Durga )').should('be.visible')
        cy.get(".col-md-3.staffCol").last().find("img").should("exist").and("have.attr", "src", "assets/img/Vidya-HM-LowerPrimary.jpg ").next('div:contains( Smt Vidya Madhavan )').should('be.visible')
        cy.get('a[href="/preNursery"]').should('exist').children('h4:contains(Pre-Nursery)').should('be.visible')
        cy.get('a[href="/nursery"]').should('exist').children('h4:contains(Nursery)').should('be.visible')
        cy.get('a[href="/primary"]').should('exist').children('h4:contains(Primary School)').should('be.visible')
    })
    it('When User click on Pre-Nursery link , should navigte to pre-nursery page ', () => {
        cy.get('a[href="/school"]').first().click()
        cy.get('a[href="/preNursery%20"]').parent().parent().next().find('a[href="/preNursery"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/preNursery')
        cy.contains('h4', 'Our Philosophy').should('be.visible')
            .next('h4').should('have.text', 'Pre-school is the first experience for many children in a structured setting with teachers and group of children.').should('be.visible')
            .next('p').should('have.text', 'It’s an opportunity to learn, to share, to follow instructions and begin the foundation for learning. Every child has a unique way of learning and responding to the given learning environment. So activities are created around the preferred learning style that empowers the children to think and explore. Hence our school has adopted a unique concept of “Play, Learn and Grow.”').should('be.visible')
    })
    it('When User click on Nursery link , should navigte to nursery page ', () => {
        cy.get('a[href="/school"]').first().click()
        cy.get('a[href="/nursery%20"]').parent().parent().next().find('a[href="/nursery"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/nursery')
        cy.contains('h4', 'Our Philosophy').should('be.visible').next('h4:contains(Curriculum development is the main motto.)').should('be.visible')
            .next('p').should('have.text', 'Innovations are encouraged for effective relationship between teaching and learning, to help imbibe different perspectives within each subject area. Students become participants in learning, and their learning becomes linked to their life outside the school.').should('be.visible')
            .next('p').should('have.text', 'Children settle down in the new environment, perfect their co-ordination, gradually improve their concentration and exhibit incredible creativity.').should('be.visible')
            .next('p').should('have.text', 'Students are encouraged to actively participate in various activities.').should('be.visible')
    })
    it('When User click on Primary school link,should navigte to primary school page ', () => {
        cy.get('a[href="/school"]').first().click()
        cy.get('a[href="/primary%20"]').parent().parent().next().find('a[href="/primary"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/primary')
        cy.contains('h4', 'Academics').should('be.visible')
            .next('p').should('have.text', 'The V.V.S.G.C.School is a co-education institution with English as the medium of instruction. The school follows the Karnataka State Board System which has been upgraded recently to the National Curriculum. The institution uses the standard books recommended by the DPI of the State Government. Additional books and reading material are utilized along with technology for enhanced learning.').should('be.visible')
            .next('p').should('have.text', 'Our institution aims at providing contemporary knowledge and skills to students through creative and innovative methods that stimulate thinking and motivate them to develop into well-moulded, responsible personalities. Our focus is on conceptual learning through a mix of both traditional chalk and talk and modern methods of teaching using technology, project work, dramatization and hands-on experience.').should('be.visible')
            .next('p').should('have.text', 'Technology offers unlimited new ways of teaching and learning.').should('be.visible')
    })
    it('When User click on Teaching Fraternity link,should navigte to Teaching Fraternity page ', () => {
        cy.get('a[href="/school"]').first().click()
        cy.get('a[href="/school/teachingFraternity"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/school/teachingFraternity')
        cy.contains('h4', ' From the desk of Principal ').should('be.visible')
            .next('p').should('have.text', 'Changing school system demands clarity of thought, a certain amount of risk taking, a thorough knowledge and belief in what we wish to accomplish and a systematic approach to achieving those goals.').should('be.visible')
            .next('p').should('have.text', 'Technology is being used in ways that will help students reap rich dividends. It creates a learning environment that is vibrant and at the same time friendly. The school offers a host of interesting and exciting programs to raise teaching – learning standards.').should('be.visible')
            .next('p').should('have.text', 'Thus, with all this supports we lead our students to acquire personal developments and accomplishment. Embedded in the vision are our culture, beliefs, values, purposes and goals that serve as the mettle of this temple of learning developed on the watchword:“In pursuit of Excellence in Quality Education”').should('be.visible')
        cy.contains('h4', ' From the desk of Principal ').parent('div').prev('div').children("img").should("exist").and("have.attr", "src", "assets/img/Principal.jpg").next().children('strong:contains(Principal: Smt. Gita Venkatesh)').should('be.visible')
        cy.get(".col-md-3.staffCol").first().find("img").should("exist").and("have.attr", "src", "assets/img/Padmaja-HM-Playhome.jpg").next('div:contains(Smt Padmaja M N )').should('be.visible')
        cy.get(".col-md-3.staffCol").first().next().find("img").should("exist").and("have.attr", "src", "assets/img/Vani-HM-Nursery.jpg").next('div:contains(Smt Vani Sridhar B S )').should('be.visible')
        cy.get(".col-md-3.staffCol").first().next().next().find("img").should("exist").and("have.attr", "src", "assets/img/Kanaka-HM-HigerPrimary.jpg ").next('div:contains( Smt Kanaka Durga )').should('be.visible')
        cy.get(".col-md-3.staffCol").last().find("img").should("exist").and("have.attr", "src", "assets/img/Headmistress of Higher Primary .png").next('div:contains(Smt Vidya Madhavan)').should('be.visible')
        cy.get('a[href="/preNursery"]').should('exist').children('h4:contains(Pre-Nursery)').should('be.visible')
        cy.get('a[href="/nursery"]').should('exist').children('h4:contains(Nursery)').should('be.visible')
        cy.get('a[href="/primary"]').should('exist').children('h4:contains(Primary School)').should('be.visible')
    })
    it.only('When User click on School Schedule link , should navigte to School Schedule page ', () => {
        cy.get('a[href="/school"]').first().click()
        cy.get('a[href="/school/schoolSchedule"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/school/schoolSchedule')
        cy.contains('h4', 'Holiday List for Academic Year 2016-17').should('be.visible').next('table').get('thead tr th').each((th, index) => cy.wrap(th).should('have.text', ['SN', 'Date', 'Day', 'Holidays','SN', 'Date', 'Day', 'Events'][index]))
        cy.contains('h4', 'Celebrations At School 2016-17').should('be.visible').next('table').get('thead tr th').each((th, index) => cy.wrap(th).should('have.text', ['SN', 'Date', 'Day', 'Holidays','SN', 'Date', 'Day', 'Events'][index]))
    })
    it('When User click on Train The Teacher link , should navigte to Train The Teacher page ', () => {
        cy.get('a[href="/school"]').first().click()
        cy.get('a[href="/school/trainTheTeacher"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/school/trainTheTeacher')
        cy.contains('h4', 'Faculty Development Programme:').should('be.visible')
        .next('p').should('have.text','‘Teach the teachers’ is a continuous on-going programme which aims at organising lectures, workshops and demonstrations in educational and related fields on topics of general interest to the teaching community. Some of the events conducted in the recent past have been :').should('be.visible')
        .next('ul').children('li').each((item, index) => {
            const expectedTexts = ['Leadership Program', 'Safe Child', 'Classroom Management', 'Learning Difficulties', 'Physics Workshop', 'Mission Mars', 'K-yan']
            cy.contains('li', expectedTexts[index])
          })   
    })
    it.only('When User click on Achievements link , should navigte to Achievements page ', () => {
        cy.get('a[href="/school"]').first().click()
        cy.get('a[href="/school/achievements"]').click()
        cy.url().should('eq', Cypress.config().baseUrl + '/school/achievements')
        cy.contains('h4', 'SCHOLASTIC ACHIEVERS :').should('be.visible')
        .next('p').should('have.text','First 10 Toppers of Std VII (2014 – 15)').should('be.visible')
        cy.contains('h4', 'NON SCHOLASTIC ACHIEVERS :').should('be.visible')
        .next('p').should('have.text','International Level Achievers').should('be.visible').next('ul')
        .next('p').should('have.text','National Level Achievers').should('be.visible').next('ul')
        .next('p').should('have.text','State Level Achievers').should('be.visible').next('ul')
    })
    it('When User click on news link , should navigte to News page ', () => {
        cy.get('a[href="/school"]').first().click()
        cy.get('a[href="/school/news"]').first().click()
        cy.url().should('eq', Cypress.config().baseUrl + '/school/news')
        cy.contains('h4', 'News & Events').should('be.visible')
    })

})